Add tox.ini, pyproject.toml & mypy. Add pylint to the GitHub Action view
Toxify the CI for not having to push to run CI, just run tox locally

Signed-off-by: Bernhard Kaindl <bernhard.kaindl@cloud.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,53 +1,93 @@
+# actions can be run locally using act and docker, on Fedora 37 also with podman, using:
+# https://github.com/nektos/act
+# sudo dnf install -y act-cli podman-docker
+# act --bind --container-daemon-socket $XDG_RUNTIME_DIR/podman/podman.sock -W .github/workflows/main.yml
+
 name: Unit tests
 
+# Checks can be skipped by adding "skip-checks: true" to a commit message,
+# or requested by adding "request-checks: true" if disabled by default for pushes:
+# https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks#skipping-and-requesting-checks-for-individual-commits
 on: [push, pull_request]
+env:
+  PYTHONWARNINGS: "ignore:DEPRECATION"
+  PIP_ROOT_USER_ACTION: "ignore"     # For local testing using act-cli
+  PIP_NO_WARN_SCRIPT_LOCATION: "0"   # For local testing using act-cli
+  PIP_DISABLE_PIP_VERSION_CHECK: "1" # Reduce noise in logs
 
 jobs:
   test:
     strategy:
+      # See: https://github.com/xenserver/python-libs/pull/26#discussion_r1179482169
+      # max-parallel: 1
+      # Want to get the results of all the tests, don't terminate all on a fail:
+      fail-fast: false
       matrix:
         include:
+        - python-version: '3.11'
+          os: ubuntu-latest
+        # This tests with Python 2.7 and with Ubuntu-20.04's Python 3.8 for combined py2+3 coverage:
         - python-version: '2.7'
           os: ubuntu-20.04
-        - python-version: '3'
+        - python-version: '3.10'
           os: ubuntu-latest
+        - python-version: '3.9'
+          os: ubuntu-latest
+        - python-version: '3.7'
+          os: ubuntu-latest
+        - python-version: '3.6'
+          os: ubuntu-20.04
     runs-on: ${{ matrix.os }}
-
     steps:
       - uses: actions/checkout@v3
         with:
-          fetch-depth: 0
+          fetch-depth: 0  # Needed by diff-cover to get the changed lines: origin/master..HEAD
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v4
         with:
           python-version: ${{ matrix.python-version }}
 
-      - name: Install dependencies
+      - name: Provide Pylint Summary and Report on the GitHub Action's info page
+        if: ${{ matrix.python-version == 3.11 }}
         run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements-dev.txt
-          pip install -e .
+          pip install -q pylint pandas tabulate 2>&1|grep -v root ||: # Hide warning for root in local container
+          tree=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/tree/$GITHUB_REF_NAME
+          [ -n "$GITHUB_STEP_SUMMARY" ] || GITHUB_STEP_SUMMARY=pylint-summary-table.md
+          ./gen_gh_pylint_report.py xcp $GITHUB_STEP_SUMMARY $tree
 
-      - name: Test
+      - name: Install of tox4 on ubuntu-latest
+        if: ${{ startsWith(matrix.python-version, '3.') && matrix.python-version != 3.6 }}
         run: |
-          pytest --cov -rP
-          coverage xml
-          coverage html -d htmlcov-${{ matrix.python-version }}
-          coverage html -d htmlcov-tests-${{ matrix.python-version }} --include="tests/*"
-          diff-cover --compare-branch=origin/master --html-report coverage-diff-${{ matrix.python-version }}.html coverage.xml
+          pip install -q 'virtualenv<20.22' 'tox>=4.5.1' tox-gh-actions
 
-      - name: Pylint
+      # tox >= 4.0.0 is needed for using optional-dependencies from pyproject.toml, which is
+      # is not available for python <= 3.6, so use the python3.8 of Ubuntu-20.04 to install it:
+      - name: Install of tox4 on 20.04 for using optional-dependencies from pyproject.toml
+        if: ${{ matrix.python-version == 2.7 || matrix.python-version == 3.6 }}
         run: |
-          pylint --version
-          pylint --exit-zero xcp/ tests/ setup.py
-          pylint --exit-zero --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" xcp/ tests/ setup.py > pylint.txt
-          diff-quality --compare-branch=origin/master --violations=pylint --html-report pylint-diff-${{ matrix.python-version }}.html pylint.txt
+          # Need python3-tox4 for pyproject.toml/optional-dependencies/test deps:
+          set -xv;curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py
+          python3.8 get-pip.py
+          python3.8 -m pip install -q 'virtualenv<20.22' 'tox>=4.5.1' tox-gh-actions
 
-      - uses: actions/upload-artifact@v3
+      - name: Run tests with Python ${{ matrix.python-version }} >= 3.6
+        if: ${{ matrix.python-version != 2.7 }}
+        run: |
+          tox --workdir .github/workflows/.tox --recreate
+
+      - name: Generate combined test-coverage with Python 2.7 and 3.8 for upload to codecov
+        if: ${{ matrix.python-version == 2.7 }}
+        run: |
+          tox --workdir .github/workflows/.tox --recreate -e py27-test
+          tox --workdir .github/workflows/.tox --recreate -e py38-covcombine
+
+      - name: Upload coverage reports to Codecov
+        if: ${{ matrix.python-version == 2.7 }}
+        uses: codecov/codecov-action@v3
         with:
-          name: Coverage and pylint reports
-          path: |
-            coverage-diff-${{ matrix.python-version }}.html
-            pylint-diff-${{ matrix.python-version }}.html
-            htmlcov-${{ matrix.python-version }}
-            htmlcov-tests-${{ matrix.python-version }}
+          directory: .github/workflows/.tox/py38-covcombine/log
+          env_vars: OS,PYTHON
+          fail_ci_if_error: true
+          flags: unittest
+          name: py27-py38-combined
+          verbose: true
